Updating PKGBUILD file in ckbcomp directory; changes the version of the source, updates pkg sums and script in package function

diff --git a/ckbcomp/PKGBUILD b/ckbcomp/PKGBUILD
--- a/ckbcomp/PKGBUILD
+++ b/ckbcomp/PKGBUILD
@@ -3,18 +3,34 @@
 # Ex-Maintainer: 	Jeroen Bollen <jbinero at gmail dot comau>
 
 pkgname=ckbcomp
-pkgver=1.199
-pkgrel=1
+pkgver=1.203
+pkgrel=2
 pkgdesc="Compile a XKB keyboard description to a keymap suitable for loadkeys or kbdcontrol"
 arch=(any)
 url="http://anonscm.debian.org/cgit/d-i/console-setup.git/"
 license=('GPL2')
 depends=('perl')
 source=("http://ftp.de.debian.org/debian/pool/main/c/console-setup/console-setup_${pkgver}.tar.xz")
-sha512sums=('8d969de9e6c300c799fb8c58c5300112c1576768c41cd29a9185ecbf0d5c5205356439b54141f00ef4e76ceaf3dc2106cb5fd3e9ec430a205183c07bea341d96')
+sha512sums=('e73ade4a35c7d5e4986587067ab081da8b99acd1013ef2f9de63205f43a0777a917c0ce18e35f0fc95bfe22162ad56e0c92f1f9d657a27681a26d525441bcf2a')
 
 package() {
+  if [[ -d "${srcdir}/console-setup" ]]
+  then
     cd console-setup
-    install -d ${pkgdir}/usr/bin/
-    install -m755 Keyboard/ckbcomp ${pkgdir}/usr/bin/
+  elif [[ -d "${srcdir}/console-setup-${pkgver}" ]]
+  then 
+    cd console-setup-${pkgver} 
+  else
+    echo "Source directory not found.".
+    exit 1
+  fi
+
+
+  if [[ ${?} != 0 ]]
+  then
+    cd console-setup-${pkgver}
+  fi
+
+  install -d ${pkgdir}/usr/bin/
+  install -m755 Keyboard/ckbcomp ${pkgdir}/usr/bin/
 }
